# Generated by Django 3.1.12 on 2021-07-05 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='numb1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='numb2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
