# Generated by Django 3.1.12 on 2021-07-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20210705_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adding',
            name='user',
        ),
    ]
