# Generated by Django 3.1.12 on 2021-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20210705_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adding',
            name='correct',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='adding',
            name='wrong',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
