# Generated by Django 3.1.12 on 2021-07-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_auto_20210705_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_count', models.IntegerField(blank=True, null=True)),
                ('AddingTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.adding')),
            ],
        ),
    ]
