# Generated by Django 3.1.12 on 2021-07-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_auto_20210710_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='AddingTable',
            new_name='user',
        ),
    ]
