# Generated by Django 3.1.12 on 2021-07-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0017_auto_20210712_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='sub',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
