# Generated by Django 3.1.12 on 2021-07-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0018_star_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='dev',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='mul',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
