# Generated by Django 3.1.12 on 2021-07-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_adding_num1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adding',
            name='num1',
            field=models.IntegerField(null=True, verbose_name=3),
        ),
    ]
