# Generated by Django 3.1.12 on 2021-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0022_auto_20210712_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adding',
            name='num1',
            field=models.IntegerField(blank=True, default=85, null=True),
        ),
    ]
