# Generated by Django 3.1.12 on 2021-07-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0032_auto_20210719_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adding',
            name='num1',
            field=models.IntegerField(blank=True, default=95, null=True),
        ),
    ]
