# Generated by Django 3.1.12 on 2021-07-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0035_auto_20210719_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adding',
            name='num1',
            field=models.IntegerField(blank=True, default=47, null=True),
        ),
    ]
